# Generated by Django 4.2.2 on 2023-06-15 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import notes_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('audio', models.FileField(blank=True, null=True, upload_to='uploads/', validators=[notes_api.models.validate_audio])),
                ('video', models.FileField(blank=True, null=True, upload_to='uploads/', validators=[notes_api.models.validate_video])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
